export * from './client';
export * from './queries';
export * from './types';

export * as adminApi from './admin';
export * as aiApi from './ai';
export * as apiKeysApi from './apiKeys';
export * as areasApi from './areas';
export * as authApi from './auth';
export * as billingApi from './billing';
export * as changesApi from './changes';
export * as glossaryApi from './glossary';
export * as indicatorsApi from './indicators';
export * as intelApi from './intel';
export * as jobsApi from './jobs';
export * as layersApi from './layers';
export * as municipalitiesApi from './municipalities';
export * as nearbyApi from './nearby';
export * as parcelsApi from './parcels';
export * as reportsApi from './reports';
export * as searchApi from './search';
export * as suitabilityApi from './suitability';
export * as projectsApi from './projects';
